name: Destination
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: counted-names
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
