# Dependency-building stage.
FROM python:3.11.1-slim-buster AS build

ENV DEBIAN_FRONTEND="noninteractive"
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

WORKDIR /app
RUN python3 -m venv env
ENV PATH="env/bin:$PATH"

COPY requirements.txt .
RUN pip install -r requirements.txt --extra-index-url https://pkgs.dev.azure.com/quix-analytics/53f7fe95-59fe-4307-b479-2473b96de6d1/_packaging/public/pypi/simple/

# Runtime stage.
FROM python:3.11.1-slim-buster AS runtime

WORKDIR /app
COPY --from=build /app/env /app/env
ENV PATH="env/bin:$PATH"

COPY . .

ENTRYPOINT ["env/bin/python3", "main.py"]
