# Dependency-building stage.
FROM python:3.11.1-slim-buster AS build

ENV DEBIAN_FRONTEND="noninteractive"
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

WORKDIR /app
RUN python3 -m venv env
ENV PATH="env/bin:$PATH"

COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt

# Runtime stage.
FROM python:3.11.1-slim-buster AS runtime

WORKDIR /app
COPY --from=build /app/env /app/env
ENV PATH="env/bin:$PATH"

COPY . .

ENTRYPOINT ["env/bin/python3", "main.py"]
